# Generated by Django 5.0.6 on 2024-06-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatum24', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
