# Generated by Django 5.0.6 on 2024-06-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatum24', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
